apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jl5frc9g7-python
  janus-idp.io/tekton: jl5frc9g7-python
  backstage.io/kubernetes-id: jl5frc9g7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jl5frc9g7-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
